### ISSUE TITLE
Aircheap Example not working

### ISSUE THREAD

**Issue by arizonatribe** [pro-react/sample-code#5]
Due to changes in React Autosuggest, the examples for this section of the book no longer work, and the version listed in the example code (v2.1.11) is not currently available through npm. Please either fix the example code to match (their API has changed _significantly_) or provide a location where version 2.1.11 can be downloaded and used.

**Comment by cassiozen** [comment]
Done. Sorry for the inconvenience.

I chose not to change the sample code to match the Autosuggest 3.x API because it would differ too much from the book version. Instead, I created a new project called "react-autosuggest-legacy" that keeps the 2.x API while supporting React 15 and newer dependencies (such as Babel 6).
